Implementing React Redux
Salvia17/myFlix-client pull request #6
Opened 2021-04-09 15:56 UTC by Salvia17

2021-04-11 11:44 UTC, ukch requested changes
I can't figure out how to run your app. Please can you add usage instructions to the README?

2021-04-11 14:00 UTC, Salvia17 commented
The READ ME file has been added

2021-04-12 08:21 UTC, ukch requested changes
Unfortunately I am not able to log in - after creating a user and trying to log in it says my password is incorrect. Please test and fix the issues with the login flow and I will re-review.

2021-04-12 08:21 UTC, ukch commented on README.md
> +<li>parcel [path to index.html]</li>
Not everyone will have the `parcel` command installed globally. I would recommend adding it to your project's dependencies (`npm install --save-dev parcel-bundler`)

2021-04-13 16:07 UTC, Salvia17 commented
Hi Joel,

I have checked the registration view, aned it seems to be working. I have added an alert for when user tries to use existing account. I will attach a little screen grab in CF to illustrate how I can register a new user and log in, and how I get an error when I am trying to register an existing acount. Perhaps this might have been an issue? I hope it will all work this time.

2021-04-19 05:43 UTC, ukch requested changes

2021-04-19 05:43 UTC, ukch commented on src/components/main-view/main-view.jsx
> +    super();
This doesn't look right. Generally you should always pass props here - please can you explain the reason why you made this change?

2021-04-19 05:43 UTC, ukch commented on src/components/movies-list/movies-list.jsx
> +    filteredMovies = movies.filter(m => m.Title.includes(visibilityFilter));
I have noticed that this is case sensitive. It would be better if it were case-insensitive - for this you can use `.toLowerCase()` on both `visibilityFilter` and `Title`

2021-04-19 07:09 UTC, Salvia17 commented on src/components/main-view/main-view.jsx
> +    super();
To be honest I can't even remember why I have done that.. Most probably a mistake on my part. I'll pop the props back in

2021-04-19 08:41 UTC, Salvia17 commented on src/components/movies-list/movies-list.jsx
> +    filteredMovies = movies.filter(m => m.Title.includes(visibilityFilter));
I have now added .toLowerCase() and props

2021-05-25 18:55 UTC, merged